name: etalon
services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "3000:3000"
