name: etalon

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
        - ./.env
    ports:
      - "8094:8094"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mikhalexandr
      POSTGRES_PASSWORD: phptop123
      POSTGRES_DB: etalon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    build: core/minio/config
    container_name: minio
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: mikhalexandr
      MINIO_ROOT_PASSWORD: phptop123
    volumes:
      - minio_data:/var/lib/minio/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "mc alias set myminio http://localhost:9000 mikhalexandr phptop123 && mc ls myminio" ]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  postgres_data:
  redis_data:
  minio_data:
